# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_V2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_V2
#     shield: reviung41
#
---
name: Build Corne Nice Nano V2
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZMK Firmware
        uses: zmkfirmware/zmk-build-action@v2
        with:
          config: .
          board: nice_nano_v2
          shield: corne_left
          output-name: corne_left-nice_nano_v2
      - name: Build Right Half
        uses: zmkfirmware/zmk-build-action@v2
        with:
          config: .
          board: nice_nano_v2
          shield: corne_right
          output-name: corne_right-nice_nano_v2
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          path: ./firmware/*.uf2
